---
resources:
- name: repo
  type: git
  source:
    uri: http://github.com/fejnartal/concourse-selfupdate-pipeline.git
    branch: ((PR_BRANCH))

jobs:
  - name: configure-self
    plan:
    - get: repo
      trigger: true
    - set_pipeline: self
      file: repo/pipeline.yml
      vars:
        PR_BRANCH: ((PR_BRANCH))
        PR_REPO: ((PR_REPO))

  - name: bye
    plan:
      - get: repo
        trigger: true
        passed: [configure-self]
      - task: echo-bye-world
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: echo
            args: ["Bye world!"]
